### ISSUE TITLE
CitizensCMD Loading Before Citizens Is

### ISSUE THREAD

**Issue by LadyHaley** [LichtHund/CitizensCMD#8]
**Describe the bug**

It looks like its trying to load before Citizens is loaded, complaining that Citizens isnt installed, and then disabling itself.
Enabling it with the use of Plugman after the server is loaded causes no issues and the plugin then continues to work properly

**To Reproduce**
1. Turn server on
2. CitizensCMD tries to load before Citizens
3. It disables itself
4. 

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Citizens version
 - Spigot version
 - CitizensCMD version
- Java version

![image](https://user-images.githubusercontent.com/3754909/52218327-89c18780-28ee-11e9-81a8-87930140b14c.png)

https://pastebin.com/RV32aQnL

**Additional context**

**Comment by Drc-DEV** [comment]
This is strange, Citizens is listed in the softdepend list in plugin.yml

**Comment by LichtHund** [comment]
This is not a problem caused by the plugin, this has a secondary cause.
Citizens is set as softdepend on purpose, if it is set as depend it will instantly disable if Citizens is not found, making this problem even worse.
It is set as softdepend so it can be manually checked and self disabled with messages.

An example is that that server is using CitizensBooks which is also loading before Citizens.

The only thing I can do and I am already doing that (will release soon) is an option in the config to disable the self disabling of the plugin, just in case unusual things like this happens.

Thank you for opening the issue though.

**Comment by LichtHund** [comment]
Added option to disable Citizens check on startup, hopefully will help with this problem.
Simply add "citizens-check: false" to your config when you update to 2.2.
f115d9e330126320a29e3cd72f5ad077de0cd566
